//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBforMyApp1Entities : DbContext
    {
        public DBforMyApp1Entities()
            : base("name=DBforMyApp1Entities")
        {
        }

        private static DBforMyApp1Entities context_;

        public static DBforMyApp1Entities Context()
        {
            if(context_ == null)
            {
                context_ = new DBforMyApp1Entities();
            }
            return context_;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    }
}
